### DISCUSSION TITLE
Unit-tests not registering as a fail

### DISCUSSION THREAD

**Discussion by spongeBri** [re-actors/alls-green#16] [Q&A] [answered]
I would like to have a little assistance in why this particular scenario is not working.
We currently have 4 steps in our yaml

Deploy
Test (failed tests are rerun) 
Publish (Publish the results of the initial run)
Publish Retry (Publish the results of the retry run, with the collected failed tests)

Currently even if the retry has failures, all steps are made to go green.
I am aiming for all to go green only if the retry does not have any failures when it publish's.

![image](https://user-images.githubusercontent.com/111607680/201690131-689f8de8-7683-4ce7-a4b3-db8f0d54a663.png)

During the check the only step allowed to fail is the initial test publish, but the retry should not be allowed to fail as we want to catch if tests fail on the retry.
Not sure why its going green when its publishing failed results. 

``` yaml
  check:
    if: always()

    needs:
    - upload-first-run-tests
    - upload-retry-run-tests

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-failures: upload-first-run-tests
        jobs: ${{ toJSON(needs) }}
```

Any help on solving this issue would be hugely appreciated
