### ISSUE TITLE
[TODO] Implement `allow-skips`

### ISSUE THREAD

**Issue by webknjaz** [re-actors/alls-green#1]
This has been suggested by @pradyunsg.

Use-case: workflows that run jobs conditionally, depending on the files changed in associated PRs, for example — https://github.com/pypa/pip/blob/bbc7021/.github/workflows/ci.yml#L29-L49, using a change detection action like `dorny/paths-filter`.

**Comment by webknjaz** [comment]
@pradyunsg mind checking out the change?
https://github.com/re-actors/alls-green/commit/3a2de129f0713010a71314c74e33c0e3ef90e696
https://github.com/webknjaz/check-gha-test/runs/4515033319?check_suite_focus=true#step:3:59

It is currently testable via the unstable branch:
```yaml
- uses: re-actors/alls-green@unstable/v1
  id: check
  with:
    allowed-failures: failing-job0
    allowed-skips: failing-job1, skipped-job
    jobs: ${{ toJSON(needs) }}
```
