### ISSUE TITLE
The execution status still green

### ISSUE THREAD

**Issue by BuddyGlas** [re-actors/alls-green#18]
Sorry, maybe I don't understand how this action should work, but I added the check to my workflow, but I didn't get the expected result. Why is the execution status (number 1 in the screenshot) still green? 
```
  check:
    if: always()
    runs-on: [self-hosted]
    needs:
    - dev_build_int_tests

    steps:
    - name: Install python3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
```

![2022-11-29_14-57](https://user-images.githubusercontent.com/104383456/204471565-e8c26f72-46f5-463f-a941-9cac9c3942ca.png)
