### ISSUE TITLE
Cannot use this action in a chain

### ISSUE THREAD

**Issue by LecrisUT** [re-actors/alls-green#25]
Example:
```yaml
  test:
    uses: ...
    if: "! inputs.skip-tests"

  test-status:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: test
          jobs: ${{ toJSON(needs) }}
    if: always()

  build:
    needs: [ test-status ]
    uses: ...
```

The latter job is not run, probably because of the `needs` of the former

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/re-actors) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/re-actors/alls-green/issues/25">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/re-actors/alls-green/issues/25/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/re-actors/alls-green/issues/25/pledge.svg">
</picture>
</a>
