### ISSUE TITLE
Feat: add the possibility to skip a failed test from a matrix

### ISSUE THREAD

**Issue by alber70g** [re-actors/alls-green#28]
Imagine this

```yaml
  end-to-end-tests:
    name: E2E - ${{ matrix.app }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ['tools', 'docs', 'app']
```

and the `ci-gate`

```yaml
  ci-gate:
    if: always()
    needs:
      - build
      - integration-tests
      - end-to-end-tests
    runs-on: Ubuntu-latest
    steps:
      - name: Check required jobs.
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
```

I'd like to be able to "allow-failed" the `app` part of `end-to-end-tests`. Is that possible?
